#!/bin/sh

alphabet="abcdefghijkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789"

size=${1:-20}
count=${2:-3}

function randchars() {
    n=$1
    while [ $n -gt 0 ]
    do
        x=`expr $RANDOM % ${#alphabet}`
        printf '%s' "${alphabet:$x:1}"
	n=$(($n - 1))
    done
}

while [ $count -gt 0 ]
do
    randchars $size; echo
    count=$(($count - 1))
done

