name: ci-cd

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Install poetry
      uses: snok/install-poetry@v1

    - name: Install package
      run: poetry install --with=dev

    - name: Run tests with coverage
      run: poetry run pytest tests/ --cov=gitappend --cov-report=xml

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
